### ISSUE TITLE
SINTESIS_GESTION DE PROYECTOS DE SOFTWARE

### ISSUE THREAD

**Issue by magaly1311** [SistemasTecTlaxiaco/actividad-3-sintesis-magaly1311#2]
[SINTESIS DE GESTION DE PROYECTOS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-magaly1311/files/12530501/SINTESIS.DE.GESTION.DE.PROYECTOS.pdf)

**Comment by DiegoSCP117** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
